/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author charl
 */
public class UIMain extends javax.swing.JFrame
{

   /**
    Creates new form UIMain
    */
   public UIMain()
   {
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      tabContainer = new javax.swing.JTabbedPane();
      tabLogin = new javax.swing.JTabbedPane();
      tabHome = new javax.swing.JTabbedPane();
      tabBrowse = new javax.swing.JTabbedPane();
      tabAccount = new javax.swing.JTabbedPane();
      tabCart = new javax.swing.JTabbedPane();
      tabNotifications = new javax.swing.JTabbedPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Movie Rental System");
      setAlwaysOnTop(true);
      setBackground(new java.awt.Color(255, 255, 255));
      setMinimumSize(new java.awt.Dimension(640, 480));
      setName("frameMain"); // NOI18N

      tabContainer.setBackground(new java.awt.Color(255, 255, 255));
      tabContainer.setName("mainTab"); // NOI18N
      tabContainer.addTab("Login", tabLogin);

      tabHome.setBackground(new java.awt.Color(255, 255, 255));
      tabContainer.addTab("Home ", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_home_64_0_000000_none.png")), tabHome); // NOI18N

      tabBrowse.setBackground(new java.awt.Color(255, 255, 255));
      tabContainer.addTab("Browse ", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_list-ul_16_0_000000_none.png")), tabBrowse); // NOI18N

      tabAccount.setBackground(new java.awt.Color(255, 255, 255));
      tabContainer.addTab("Account ", new javax.swing.ImageIcon(getClass().getResource("/material-icons_3-0-1_account-box_16_0_000000_none.png")), tabAccount); // NOI18N

      tabCart.setBackground(new java.awt.Color(255, 255, 255));
      tabContainer.addTab("Cart ", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_shopping-cart_16_0_000000_none.png")), tabCart); // NOI18N
      tabCart.getAccessibleContext().setAccessibleDescription("");

      tabContainer.addTab("Notifications ", new javax.swing.ImageIcon(getClass().getResource("/ionicons_2-0-1_android-notifications_16_0_000000_none.png")), tabNotifications); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
      );

      tabContainer.getAccessibleContext().setAccessibleDescription("");

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new UIMain().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTabbedPane tabAccount;
   private javax.swing.JTabbedPane tabBrowse;
   private javax.swing.JTabbedPane tabCart;
   private javax.swing.JTabbedPane tabContainer;
   private javax.swing.JTabbedPane tabHome;
   private javax.swing.JTabbedPane tabLogin;
   private javax.swing.JTabbedPane tabNotifications;
   // End of variables declaration//GEN-END:variables
}
