/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author charl
 */
public class UIMain extends javax.swing.JFrame
{

   /**
    Creates new form UIMain
    */
   public UIMain()
   {
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      tabMain = new javax.swing.JTabbedPane();
      panelLogin = new javax.swing.JPanel();
      usernameLbl = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      logoImg = new javax.swing.JLabel();
      passwordLbl = new javax.swing.JLabel();
      usernameTxtFld = new javax.swing.JTextField();
      passwordTxtFld = new javax.swing.JTextField();
      panelHome = new javax.swing.JPanel();
      panelBrowse = new javax.swing.JPanel();
      panelAccount = new javax.swing.JPanel();
      panelCart = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList<>();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      jList2 = new javax.swing.JList<>();
      jScrollPane3 = new javax.swing.JScrollPane();
      jList3 = new javax.swing.JList<>();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jButton2 = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      panelNotifications = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Movie Rental System");
      setAlwaysOnTop(true);
      setBackground(new java.awt.Color(255, 255, 255));
      setMinimumSize(new java.awt.Dimension(640, 480));
      setName("frameMain"); // NOI18N

      tabMain.setBackground(new java.awt.Color(255, 255, 255));
      tabMain.setName("mainTab"); // NOI18N

      usernameLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      usernameLbl.setText("Username:");

      jLabel2.setToolTipText("");

      logoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoMedium.png"))); // NOI18N
      logoImg.setRequestFocusEnabled(false);

      passwordLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      passwordLbl.setText("Password:");

      javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
      panelLogin.setLayout(panelLoginLayout);
      panelLoginLayout.setHorizontalGroup(
         panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelLoginLayout.createSequentialGroup()
            .addGap(112, 112, 112)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(passwordLbl)
               .addComponent(usernameLbl))
            .addGap(22, 22, 22)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelLoginLayout.createSequentialGroup()
                  .addComponent(logoImg)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel2))
               .addGroup(panelLoginLayout.createSequentialGroup()
                  .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 157, Short.MAX_VALUE))))
      );
      panelLoginLayout.setVerticalGroup(
         panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelLoginLayout.createSequentialGroup()
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelLoginLayout.createSequentialGroup()
                  .addGap(100, 100, 100)
                  .addComponent(jLabel2))
               .addGroup(panelLoginLayout.createSequentialGroup()
                  .addGap(77, 77, 77)
                  .addComponent(logoImg)))
            .addGap(48, 48, 48)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(usernameLbl)
               .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordLbl)
               .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(109, Short.MAX_VALUE))
      );

      tabMain.addTab("Login", panelLogin);

      javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
      panelHome.setLayout(panelHomeLayout);
      panelHomeLayout.setHorizontalGroup(
         panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 644, Short.MAX_VALUE)
      );
      panelHomeLayout.setVerticalGroup(
         panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 454, Short.MAX_VALUE)
      );

      tabMain.addTab("Home ", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_home_64_0_000000_none.png")), panelHome); // NOI18N

      javax.swing.GroupLayout panelBrowseLayout = new javax.swing.GroupLayout(panelBrowse);
      panelBrowse.setLayout(panelBrowseLayout);
      panelBrowseLayout.setHorizontalGroup(
         panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 644, Short.MAX_VALUE)
      );
      panelBrowseLayout.setVerticalGroup(
         panelBrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 454, Short.MAX_VALUE)
      );

      tabMain.addTab("Browse ", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_list-ul_16_0_000000_none.png")), panelBrowse); // NOI18N

      javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
      panelAccount.setLayout(panelAccountLayout);
      panelAccountLayout.setHorizontalGroup(
         panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 644, Short.MAX_VALUE)
      );
      panelAccountLayout.setVerticalGroup(
         panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 454, Short.MAX_VALUE)
      );

      tabMain.addTab("Account ", new javax.swing.ImageIcon(getClass().getResource("/material-icons_3-0-1_account-box_16_0_000000_none.png")), panelAccount); // NOI18N

      jList1.setModel(new javax.swing.AbstractListModel<String>()
      {
         String[] strings = { "$5.99", "$5.99", "$5.99", "$5.99", "$5.99" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(jList1);

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      jLabel1.setText("Cart");

      jLabel3.setText("Title");

      jList2.setModel(new javax.swing.AbstractListModel<String>()
      {
         String[] strings = { "1", "1", "1", "1", "2" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane2.setViewportView(jList2);

      jList3.setModel(new javax.swing.AbstractListModel<String>()
      {
         String[] strings = { "Finding Dory", "Captain America: Civil War", "Star Trek Beyond", "The BFG", "The Secret Life of Pets" };
         public int getSize() { return strings.length; }
         public String getElementAt(int i) { return strings[i]; }
      });
      jScrollPane3.setViewportView(jList3);

      jLabel4.setText("Price");

      jLabel5.setText("Quantity");

      jButton2.setText("Remove Item");

      jButton1.setText("Edit Quantity");

      jButton4.setText("Checkout");

      javax.swing.GroupLayout panelCartLayout = new javax.swing.GroupLayout(panelCart);
      panelCart.setLayout(panelCartLayout);
      panelCartLayout.setHorizontalGroup(
         panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCartLayout.createSequentialGroup()
            .addContainerGap(12, Short.MAX_VALUE)
            .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(panelCartLayout.createSequentialGroup()
                     .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(panelCartLayout.createSequentialGroup()
                     .addComponent(jButton2)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jButton1)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jButton4))))
            .addContainerGap())
      );
      panelCartLayout.setVerticalGroup(
         panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelCartLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(32, 32, 32)
            .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
               .addComponent(jScrollPane1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton2)
               .addComponent(jButton1)
               .addComponent(jButton4))
            .addContainerGap(66, Short.MAX_VALUE))
      );

      tabMain.addTab("Cart", new javax.swing.ImageIcon(getClass().getResource("/font-awesome_4-7-0_shopping-cart_16_0_000000_none.png")), panelCart, ""); // NOI18N

      javax.swing.GroupLayout panelNotificationsLayout = new javax.swing.GroupLayout(panelNotifications);
      panelNotifications.setLayout(panelNotificationsLayout);
      panelNotificationsLayout.setHorizontalGroup(
         panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 644, Short.MAX_VALUE)
      );
      panelNotificationsLayout.setVerticalGroup(
         panelNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 454, Short.MAX_VALUE)
      );

      tabMain.addTab("Notifications", new javax.swing.ImageIcon(getClass().getResource("/ionicons_2-0-1_android-notifications_16_0_000000_none.png")), panelNotifications); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabMain)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(tabMain, javax.swing.GroupLayout.Alignment.TRAILING)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new UIMain().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JList<String> jList1;
   private javax.swing.JList<String> jList2;
   private javax.swing.JList<String> jList3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JLabel logoImg;
   private javax.swing.JPanel panelAccount;
   private javax.swing.JPanel panelBrowse;
   private javax.swing.JPanel panelCart;
   private javax.swing.JPanel panelHome;
   private javax.swing.JPanel panelLogin;
   private javax.swing.JPanel panelNotifications;
   private javax.swing.JLabel passwordLbl;
   private javax.swing.JTextField passwordTxtFld;
   private javax.swing.JTabbedPane tabMain;
   private javax.swing.JLabel usernameLbl;
   private javax.swing.JTextField usernameTxtFld;
   // End of variables declaration//GEN-END:variables
}
